spring:
  # 配置数据源
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://172.16.34.128:3306/gulimall_ums?useSSH=false
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 172.16.34.128:8848
  application:
    name: gulimall-member

server:
  port: 8000

mybatis-plus:
  global-config:
    db-config:
      # 全局配置id自增
      id-type: auto
  # 指定mybatis的sql映射文件路径
  mapper-locations: classpath:/mapper/**/*Dao.xml