spring:
  # 服务链路追踪
  zipkin:
    # 服务名
    base-url: http://172.16.156.128:9411/
    # 关闭服务发现，否则 SpringCloud 会把 zipkin 的 url 当作服务名
    discovery-client-enabled: false
    sender:
      # 使用http进行传输
      type: web
  sleuth:
    sampler:
      # 设置抽样采集器，1=100%
      probability: 1
  # 配置数据源
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://172.16.156.128:3306/gulimall_ums?useSSH=false
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 172.16.156.128:8848

    sentinel:
      transport:
        dashboard: 172.16.156.128:8080
  application:
    name: gulimall-member

  thymeleaf:
    cache: false

  redis:
    host: 172.16.156.128

  session:
    store-type: redis

server:
  port: 8000

mybatis-plus:
  global-config:
    db-config:
      # 全局配置id自增
      id-type: auto
  # 指定mybatis的sql映射文件路径
  mapper-locations: classpath:/mapper/**/*Dao.xml

management:
  endpoints:
    web:
      exposure:
        include: '*'