spring:
  profiles:
    group:
      dev:
        # privacy 隐私环境，内含不允许公开的信息，在git中忽略
        - privacy
    active: dev
  #  配置数据源
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://192.168.135.128:3306/gulimall_pms?useSSH=false
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.135.128:8848
  application:
    name: gulimall-product
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

# 关闭 thymeleaf 缓存
  thymeleaf:
    cache: false

# 配置 redis
  redis:
    host: 192.168.135.128

  # SpringCache配置
  cache:
    type: redis
    redis:
      time-to-live: 300000
      use-key-prefix: true
      # 是否缓存空值，可解决缓存穿透问题
      cache-null-values: true

server:
  port: 10000

mybatis-plus:
  #  配置mybatis的sql映射文件路径
  mapper-locations: classpath:/mapper/**/*Dao.xml
  global-config:
    db-config:
      # 全局配置id自增
      id-type: auto
      # 配置逻辑删除标识
      logic-delete-value: 1
      # 逻辑不删除
      logic-not-delete-value: 0

logging:
  level:
    top.ctong.gulimall: debug

gulimall:
  thread:
    core-pool-size: 20
    maximum-pool-size: 200
    keep-alive-time: 10
