spring:
  #  配置数据源
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://127.0.0.1:3306/gulimall_pms?useSSH=false
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-product

server:
  port: 10000

mybatis-plus:
  #  配置mybatis的sql映射文件路径
  mapper-locations: classpath:/mapper/**/*Dao.xml
  global-config:
    db-config:
      # 全局配置id自增
      id-type: auto