spring:
  application:
    name: gulimall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.135.128:8848
  redis:
    host: 192.168.135.128
    port: 6379
server:
  port: 20000
debug: true