mybatis-plus:
  # 全局配置id类型自增
  global-config:
    db-config:
      id-type: auto
  # mybatis的sql映射文件
  mapper-locations: classpath:/mapper/**/*.Dao.xml


server:
  port: 9010

spring:
  profiles:
    active: dev
  application:
    name: gulimall-order

  cloud:
    nacos:
      discovery:
        server-addr: 172.16.156.128:8848
    sentinel:
      transport:
        dashboard: 172.16.156.128:8080

  # redis 配置
  redis:
    host: 172.16.156.128

  # spring session 配置
  session:
    store-type: redis

  # 配置数据源
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://172.16.156.128:3306/gulimall_oms?useSSH=false
    driver-class-name: com.mysql.cj.jdbc.Driver

  rabbitmq:
    host: 172.16.156.128
    listener:
      simple:
        acknowledge-mode: manual
    port: 5672
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    virtual-host: /

  thymeleaf:
    cache: false
# 谷粒商城配置项
gulimall:
  thread:
    core-pool-size: 20
    maximum-pool-size: 200
    keep-alive-time: 10
management:
  endpoints:
    web:
      exposure:
        include: *
