server:
  port: 9000

spring:
  # 配置数据源
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/gulimall_oms?useSSH=false
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  # 全局配置id类型自增
  global-config:
    db-config:
      id-type: auto
  # mybatis的sql映射文件
  mapper-locations: classpath:/mapper/**/*.Dao.xml
