
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.156.128:8848
  thymeleaf:
    cache: false

  redis:
    host: 172.16.156.128
  session:
    store-type: redis
server:
  port: 12000
