
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.135.128:8848
  thymeleaf:
    cache: false

  redis:
    host: 192.168.135.128
  session:
    store-type: redis
server:
  port: 12000
