spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.135.128:8848

alibaba:
  cloud:
    access-key: LTAI5tLFg91oWipAtcVBdASd
    secret-key: 7FtKhOUqhi0eXpagvb0Kxf8cq6tMzn
    oss:
      endpoint: oss-cn-guangzhou.aliyuncs.com
    sms:
      host: https://gyytz.market.alicloudapi.com
      path: /sms/smsSend
      app-code: # 秘密
      sms-sign-id: 2e65b1bb3d054466b82f0c9d125465e2
      template-id: 908e94ccf08b4476ba6c876d13f084ad