spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.156.128:8848
    sentinel:
      transport:
        dashboard: 172.16.156.128:8080
  profiles:
    active: private

alibaba:
  cloud:
    access-key: # 你的access-key
    secret-key: # 你阿里云的secret-key
    oss:
      endpoint: oss-cn-guangzhou.aliyuncs.com
    sms:
      host: https://gyytz.market.alicloudapi.com
      path: /sms/smsSend
      app-code: # 你的短信app-code
      sms-sign-id: # 你的短信sms-sign-id
      template-id: # 你的短信template-id