server:
  port: 11000

spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/gulimall_oms?useSSH=false
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Dao.xml
  global-config:
    db-config:
      id-type: auto