server:
  port: 11000


spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://172.16.156.128:3306/gulimall_wms?useSSH=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  cloud:
    nacos:
      config:
        enabled: false
      discovery:
        server-addr: 172.16.156.128:8848

  application:
    name: gulimall-ware
    
  rabbitmq:
    host: 172.16.156.128
    listener:
      simple:
        acknowledge-mode: manual
    port: 5672
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    virtual-host: /

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Dao.xml
  global-config:
    db-config:
      id-type: auto
logging:
  level:
    top.ctong.gulimall.ware: debug
