server:
  port: 11000


spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://192.168.226.128:3306/gulimall_wms?useSSH=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  cloud:
    nacos:
      config:
        enabled: false
      discovery:
        server-addr: 192.168.226.128:8848
  application:
    name: gulimall-ware

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Dao.xml
  global-config:
    db-config:
      id-type: auto
logging:
  level:
    top.ctong.gulimall.ware: debug
